openapi: 3.0.1
info:
  title: DynamicSearch
  version: '1.0'
  contact:
   email: jovan.dodic89@gmail.com
paths:
  /api/v1/search/{clientName}/{schemaName}/{entityName}:
    get:
      tags:
        - Search Client data
      parameters:
        - name: searchClientQueryCommand
          in: query
          schema:
            $ref: '#/components/schemas/SearchClientQueryCommand'
        - name: clientName
          in: path
          required: true
          schema:
            type: string
        - name: schemaName
          in: path
          required: true
          schema:
            type: string
        - name: entityName
          in: path
          required: true
          schema:
            type: string
        - name: searchString
          in: query
          required: false
          schema:
            type: string
        - name: page
          in: query
          required: false
          schema:
            type: integer
        - name: pageLimit
          in: query
          required: false
          schema:
            type: integer
        - name: orderBy
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SearchClientResponseDto'
            application/json:
              schema:
                $ref: '#/components/schemas/SearchClientResponseDto'
            text/json:
              schema:
                $ref: '#/components/schemas/SearchClientResponseDto'
        '204':
          description: No Content
        '400':
          description: Bad Request
        '500':
          description: Server Error
components:
  schemas:
    SearchClientQueryCommand:
      type: object
      properties:
        clientName:
          type: string
          nullable: true
        schemaName:
          type: string
          nullable: true
        entityName:
          type: string
          nullable: true
        page:
          type: integer
          format: int32
        pageLimit:
          type: integer
          format: int32
        searchString:
          type: string
          nullable: true
        orderBy:
          type: string
          nullable: true
      additionalProperties: false
    SearchClientResponseDto:
      type: object
      properties:
        totalCount:
          type: integer
          format: int32
        page:
          type: integer
          format: int32
        pageLimit:
          type: integer
          format: int32
        items:
          type: array
          items: {}
          nullable: true
      additionalProperties: false
